watchlist_urls = {
    # Webseiten & Strukturen
#    "AfD Weilheim-Schongau": "https://www.afd-weilheim-schongau.de/",
    "AfD Weilheim-Schongau News": "https://www.afd-weilheim-schongau.de/neu/",
    "AfD Bayern KV Weilheim-Schongau": "https://afdbayern.de/kreis-ortsverbaende/oberbayern/weilheim-schongau/",
    "AfD Bayern KV Garmisch-Partenkirchen": "https://afdbayern.de/kreis-ortsverbaende/oberbayern/garmisch-partenkirchen/",
    "AfD Bayern KV Starnberg": "https://afdbayern.de/kreis-ortsverbaende/oberbayern/starnberg/",
    "AfD Bayern KV Bad Tölz": "https://afdbayern.de/kreis-ortsverbaende/oberbayern/badtoelz/",
#    "AfD Bayern KV Miesbach": "https://afdbayern.de/kreis-ortsverbaende/oberbayern/oberbayern-sued/",
    "AfD Oberbayern": "https://www.afd-oberbayern.de/",
    "AfD Miesbach": "https://www.afd-miesbach.de/",
    "AfD Miesbach News": "https://www.afd-miesbach.de/corona-fakten-medien-2/",
    "AfD Ulrich Singer": "https://singer-afd.de/",
#    "AfD Bad Tölz": "https://www.afd-toelz.de/",
    "AfD Bad Tölz News": "https://www.afd-toelz.de/pressemitteilungen-des-afd-kreisverbandes-toelz/",
    "AfD Starnberg": "https://afd-starnberg.de/",
    # Social Media
    "Twitter Pauline Pezold": "https://nitter.space/PaulinePezold",
    "Twitter Politico Europe": "https://nitter.space/POLITICOEurope",
    "Twitter Marie-Therese Kaiser": "https://nitter.space/hallofraukaiser",
    "Twitter AfD": "https://nitter.space/AfD",
    "Twitter AfD Bundestag": "https://nitter.space/AfDimBundestag",
    "Twitter Gerrit Huy": "https://nitter.space/GerritHuy",
    "Twitter Benjamin Nolte": "https://nitter.space/BenjaminNolte3",
    "Twitter Alexander Gauland": "https://nitter.space/ag_afd",
    "Twitter Ingo Hahn": "https://nitter.space/IngoHahnAfD",
    "Twitter Alice Weidel": "https://nitter.space/Alice_Weidel",
    "Twitter Björn Höcke": "https://nitter.space/BjoernHoecke",
    "Twitter Beatrix von Storch": "https://nitter.space/Beatrix_vStorch",
    "Twitter Tino Chrupalla": "https://nitter.space/Tino_Chrupalla",
    "Twitter Hannes Gnauck": "https://nitter.space/Hannes_Gnauck",
    "Twitter Sven Kachelmann": "https://nitter.space/SvenKachelmann",
    "Twitter Tomasz Frölich": "https://nitter.space/TomaszFroelich",
    "Twitter Franz Schmid": "https://nitter.space/FranzSchmid_AfD",
    "Twitter Dirk Brandes": "https://nitter.space/DirkBrandes74",
    "Twitter Klaus Esser": "https://nitter.space/klausesser_nrw",
    "Twitter Julia Klöckner": "https://nitter.space/JuliaKloeckner"
}
